product_database/catalog/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^profile/(?P<pk>[-\w]+)/edit/$', views.edit_profile, name='edit'),
    re_path(r'^register/$', views.register, name='register'),
    path('addproducttofavorite/<int:product_id>', views.add_product_to_favorite, name='add_product_to_favorite'),
    path('deleteproductfromfavorite/<int:product_id>', views.delete_product_from_favorite, name='delete_product_from_favorite'),
    path('adddishtofavorite/<int:dish_id>', views.add_dish_to_favorite, name='add_dish_to_favorite'),
    path('deletedishfromfavorite/<int:dish_id>', views.delete_product_from_favorite, name='delete_dish_from_favorite'),
    re_path(r'^bnfs/$', views.BalancedNutritionFormulaListView.as_view(), name='bnfs'),
    re_path(r'^products/$', views.ProductListView.as_view(), name='products'),
    re_path(r'^prices/$', views.PriceListView.as_view(), name='prices'),
    re_path(r'^dishes/$', views.DishListView.as_view(), name='dishes'),
    re_path(r'^kitchen-utensils/$', views.KitchenUtensilListView.as_view(), name='kitchen_utensils'),
    re_path(r'^bnf/(?P<pk>\d+)$', views.BalancedNutritionFormulaDetailView.as_view(), name='bnf-detail'),
    re_path(r'^profile/(?P<pk>\d+)$', views.ProfileDetailView.as_view(), name='profile-detail'),
    re_path(r'^kitchen-utensil/(?P<pk>\d+)$', views.KitchenUtensilDetailView.as_view(), name='kitchen_utensil_detail'),
    re_path(r'^dish/(?P<pk>\d+)$', views.DishDetailView.as_view(), name='dish-detail'),
    re_path(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    re_path(r'^stores/$', views.StoreListView.as_view(), name='stores'),
    re_path(r'^store/(?P<pk>\d+)$', views.StoreDetailView.as_view(), name='store-detail'),
    re_path(r'^my-products/$', views.UsersProductsListView.as_view(), name='my-products'),
    re_path(r'^my-stores/$', views.UsersStoresListView.as_view(), name='my-stores'),
    re_path(r'^my-prices/$', views.UsersPricesListView.as_view(), name='my-prices'),
    re_path(r'^my-dishes/$', views.UsersDishesListView.as_view(), name='my-dishes'),
    re_path(r'^my-kitchen-utensils/$', views.UsersKitchenUtensilsListView.as_view(), name='my-kitchen-utensils'),
    re_path(r'^my-favorite-products/$', views.UsersFavoriteProductsListView.as_view(), name='my-favorite-products'),
    re_path(r'^my-favorite-dishes/$', views.UsersFavoriteDishesListView.as_view(), name='my-favorite-dishes'),
    re_path(r'^bnf/(?P<pk>[-\w]+)/renew-bnf/$', views.renew_balanced_nutrition_formula, name='renew-bnf'),
    re_path(r'^product/(?P<pk>[-\w]+)/renew-product/$', views.renew_product, name='renew-product'),
    re_path(r'^store/(?P<pk>[-\w]+)/renew-store/$', views.renew_store, name='renew-store'),
    re_path(r'^price/(?P<pk>[-\w]+)/renew-price/$', views.renew_price, name='renew-price'),
    re_path(r'^kitchen-utensil/(?P<pk>[-\w]+)/renew-kitchen-utensil/$', views.renew_kitchen_utensil, name='renew-kitchen-utensil'),
    re_path(r'^dish/(?P<pk>[-\w]+)/renew-dish/$', views.renew_dish, name='renew-dish'),
    re_path(r'^product/create/$', views.ProductCreate.as_view(), name='product_create'),
    re_path(r'^product/(?P<pk>\d+)/delete/$', views.ProductDelete.as_view(), name='product_delete'),
    re_path(r'^store/create/$', views.StoreCreate.as_view(), name='store_create'),
    re_path(r'^store/(?P<pk>\d+)/delete/$', views.StoreDelete.as_view(), name='store_delete'),
    re_path(r'^dish/(?P<pk>\d+)/delete/$', views.DishDelete.as_view(), name='dish_delete'),
    re_path(r'^kitchen-utensil/(?P<pk>\d+)/delete/$', views.KitchenUtensilDelete.as_view(), name='kitchen_utensil_delete'),
    re_path(r'^price/create/$', views.PriceCreate.as_view(), name='price_create'),
    re_path(r'^dish/create/$', views.create_dish, name='dish_create'),
    re_path(r'^kitchen-utensil/create/$', views.KitchenUtensilCreate.as_view(), name='kitchen_utensil_create'),
    re_path(r'^kitchen-utensil/(?P<pk>\d+)/delete/$', views.KitchenUtensilDelete.as_view(), name='kitchen_utensil_delete'),
    re_path(r'^price/(?P<pk>\d+)/delete/$', views.PriceDelete.as_view(), name='price_delete'),
    re_path(r'^menu/create/$', views.calculate_formula, name='calculate_formula'),
]

product_database/product_database/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product_database/catalog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from .choices import PAGS, UNITS, SEXES, ALL_YEARS
from location_field.models.plain import PlainLocationField


class NutritionData(models.Model):
    proteins = models.FloatField()
    proteins_including_animals = models.FloatField()
    fat = models.FloatField()
    fat_including_animals = models.FloatField()
    digestible_carbohydrates = models.FloatField()
    digestible_carbohydrates_incl_m_and_d = models.FloatField()
    dietary_fiber = models.FloatField()
    dietary_fiber_including_fiber_and_pectin = models.FloatField()
    polyunsaturated_acid = models.FloatField()
    saturated_acid = models.FloatField()
    monounsaturated_acid = models.FloatField()
    calcium_in_mg = models.FloatField()
    phosphorus_in_mg = models.FloatField()
    magnesium_in_mg = models.FloatField()
    potassium_in_mg = models.FloatField()
    sodium_in_mg = models.FloatField()
    chlorine_in_mg = models.FloatField()
    sulfur_in_mg = models.FloatField()
    iron_in_mg = models.FloatField()
    zinc_in_mg = models.FloatField()
    iodine_in_mg = models.FloatField()
    fluorine_in_mg = models.FloatField()
    thiamine_vitamin_B1_in_mg = models.FloatField()
    riboflavin_vitamin_B2_in_mg = models.FloatField()
    pyridoxine_vitamin_B6_in_mg = models.FloatField()
    pantothenic_acid_vitamin_B3_in_mg = models.FloatField()
    folacin_acid_vitamin_B9_in_mcg = models.FloatField()
    cobalamin_acid_vitamin_B12_in_mcg = models.FloatField()
    niacin_vitamin_PP_in_mg = models.FloatField()
    ascorbic_acid_vitamin_C_in_mg = models.FloatField()
    retinol_vitamin_A_in_mcg = models.FloatField()
    tocopherol_vitamin_E_in_mg = models.FloatField()
    cholecalciferol_vitamin_D_in_mcg = models.FloatField()
    energy_value_in_kcal = models.FloatField()


class MenuForMultipleDays(models.Model):
    list_of_menus = models.ManyToManyField('MenuForOneDay')


class MenuForOneDay(models.Model):
    breakfast = models.ForeignKey('Dish', related_name='breakfast', on_delete=models.CASCADE)
    dinner = models.ForeignKey('Dish', related_name='dinner', on_delete=models.CASCADE)
    evening_meal = models.ForeignKey('Dish', related_name='evening_meal', on_delete=models.CASCADE)


class BalancedNutritionFormula(models.Model):
    country = models.CharField(max_length=255)
    humans_attributes = models.ManyToManyField('HumanAttributes', blank=True)
    #who_added = models.ForeignKey(User, on_delete=models.CASCADE, related_name='who_added_to_balanced_nutrition_formula_type')

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('bnf-detail', args=[str(self.id)])


class HumanAttributes(models.Model):
    age = models.CharField(max_length=100, choices=ALL_YEARS, default='1')
    sex = models.CharField(max_length=100, choices=SEXES, default='m')
    pag = models.CharField(max_length=100, choices=PAGS, default='k')
    cpa = models.FloatField()
    weight = models.FloatField()
    proteins = models.FloatField()
    proteins_including_animals = models.FloatField()
    fat = models.FloatField()
    fat_including_animals = models.FloatField()
    digestible_carbohydrates = models.FloatField()
    digestible_carbohydrates_incl_m_and_d = models.FloatField()
    dietary_fiber = models.FloatField()
    dietary_fiber_including_fiber_and_pectin = models.FloatField()
    polyunsaturated_acid = models.FloatField()
    saturated_acid = models.FloatField()
    monounsaturated_acid = models.FloatField()
    calcium_in_mg = models.FloatField()
    phosphorus_in_mg = models.FloatField()
    magnesium_in_mg = models.FloatField()
    potassium_in_mg = models.FloatField()
    sodium_in_mg = models.FloatField()
    chlorine_in_mg = models.FloatField()
    sulfur_in_mg = models.FloatField()
    iron_in_mg = models.FloatField()
    zinc_in_mg = models.FloatField()
    iodine_in_mg = models.FloatField()
    fluorine_in_mg = models.FloatField()
    thiamine_vitamin_B1_in_mg = models.FloatField()
    riboflavin_vitamin_B2_in_mg = models.FloatField()
    pyridoxine_vitamin_B6_in_mg = models.FloatField()
    pantothenic_acid_vitamin_B3_in_mg = models.FloatField()
    folacin_acid_vitamin_B9_in_mcg = models.FloatField()
    cobalamin_acid_vitamin_B12_in_mcg = models.FloatField()
    niacin_vitamin_PP_in_mg = models.FloatField()
    ascorbic_acid_vitamin_C_in_mg = models.FloatField()
    retinol_vitamin_A_in_mcg = models.FloatField()
    tocopherol_vitamin_E_in_mg = models.FloatField()
    cholecalciferol_vitamin_D_in_mcg = models.FloatField()
    energy_value_in_kcal = models.FloatField()
    #who_added = models.ForeignKey(User, on_delete=models.CASCADE, related_name='who_added_to_human_attributes_type')
    related_model = models.ForeignKey('BalancedNutritionFormula', on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    sex = models.CharField(max_length=1, choices=SEXES, default='m')
    weight = models.FloatField(null=True)
    nursing = models.BooleanField(blank=True, null=True)
    cpa = models.CharField(max_length=3, choices=PAGS, default='i')
    country = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    location = PlainLocationField(based_fields=['country', 'city'], zoom=7, null=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('profile-detail', args=[str(self.id)])


class Product(models.Model):

    name = models.CharField(max_length=200, help_text="Enter a product name")
    favorite = models.ManyToManyField(User, blank=True, related_name='favorite_product_type')
    who_added = models.ForeignKey(User, on_delete=models.CASCADE, related_name='who_added_to_product_type')
    weight = models.FloatField()
    unit = models.CharField(max_length=10, choices=UNITS, default='kg', help_text='Choose unit')
    product_by_weight_in_packaging = models.CharField(max_length=3, choices=(('y', 'Yes'), ('n', 'No')), default='n')
    proteins_in_100_g = models.FloatField()
    proteins_in_100_g_including_animals = models.FloatField()
    fat_in_100_g = models.FloatField()
    fat_in_100_g_including_animals = models.FloatField()
    digestible_carbohydrates_in_100_g = models.FloatField()
    digestible_carbohydrates_in_100_g_incl_m_and_d = models.FloatField()
    dietary_fiber_in_100_g = models.FloatField()
    dietary_fiber_in_100_g_including_fiber_and_pectin = models.FloatField()
    polyunsaturated_acid = models.FloatField()
    saturated_acid = models.FloatField()
    monounsaturated_acid = models.FloatField()
    calcium_in_100_g_in_mg = models.FloatField()
    phosphorus_in_100_g_in_mg = models.FloatField()
    magnesium_in_100_g_in_mg = models.FloatField()
    potassium_in_100_g_in_mg = models.FloatField()
    sodium_in_100_g_in_mg = models.FloatField()
    chlorine_in_100_g_in_mg = models.FloatField()
    sulfur_in_100_g_in_mg = models.FloatField()
    iron_in_100_g_in_mg = models.FloatField()
    zinc_in_100_g_in_mg = models.FloatField()
    iodine_in_100_g_in_mg = models.FloatField()
    fluorine_in_100_g_in_mg = models.FloatField()
    thiamine_vitamin_B1_in_100_g_in_mg = models.FloatField()
    riboflavin_vitamin_B2_in_100_g_in_mg = models.FloatField()
    pyridoxine_vitamin_B6_in_100_g_in_mg = models.FloatField()
    pantothenic_acid_vitamin_B3_in_100_g_in_mg = models.FloatField()
    folacin_acid_vitamin_B9_in_100_g_in_mcg = models.FloatField()
    cobalamin_acid_vitamin_B12_in_100_g_in_mcg = models.FloatField()
    niacin_vitamin_PP_in_100_g_in_mg = models.FloatField()
    ascorbic_acid_vitamin_C_in_100_g_in_mg = models.FloatField()
    retinol_vitamin_A_in_100_g_in_mcg = models.FloatField()
    tocopherol_vitamin_E_in_100_g_in_mg = models.FloatField()
    cholecalciferol_vitamin_D_in_100_g_in_mcg = models.FloatField()
    energy_value_in_kcal = models.FloatField()

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('product-detail', args=[str(self.id)])


class Store(models.Model):

    name = models.CharField(max_length=50, help_text="Enter a store name")
    country = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    street = models.CharField(max_length=255, null=True)
    location = PlainLocationField(based_fields=['country', 'city', 'street'], zoom=7, null=True)
    who_added = models.ForeignKey(User, on_delete=models.CASCADE, related_name='who_added_to_store_type')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('store-detail', args=[str(self.id)])


class Price(models.Model):

    store = models.ForeignKey('Store', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    who_added = models.ForeignKey(User, on_delete=models.CASCADE, related_name='who_added_to_price_type')

    def __str__(self):
        return self.product.name


class ProductAmount(models.Model):

    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=3)

product_database/catalog/templates/catalog/balancednutritionformula_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Country: {{ balancednutritionformula.country }}</h1>
{% for human_attribute in balancednutritionformula.humans_attributes.all %}
<hr>
<p><strong>Age</strong> {{ human_attribute.age }}</p>
<p><strong>Sex</strong> {{ human_attribute.sex }}</p>
<p><strong>PAG</strong> {{ human_attribute.pag }}</p>
<p><strong>Cpa</strong> {{ human_attribute.cpa }}</p>
<p><strong>Weight</strong> {{ human_attribute.weight }}</p>
<p><strong>Proteins in 100 g</strong> {{ human_attribute.proteins }} </p>
<p><strong>Proteins in 100 g including animals</strong> {{ human_attribute.proteins_including_animals }} </p>
<p><strong>Fat in 100 g</strong> {{ human_attribute.fat }} </p>
<p><strong>Fat in n100 g including animals</strong> {{ human_attribute.fat_including_animals }} </p>
<p><strong>Digestible carbohydrates in 100 g</strong> {{ human_attribute.digestible_carbohydrates }} </p>
<p><strong>Digestible carbohydrates in 100 g including mono and disaccharides</strong> {{ human_attribute.digestible_carbohydrates_incl_m_and_d }} </p>
<p><strong>Dietary fiber in 100 g</strong> {{ human_attribute.dietary_fiber }} </p>
<p><strong>Dietary fiber in 100 g including fiber and pectin</strong> {{ human_attribute.dietary_fiber_including_fiber_and_pectin }} </p>
<p><strong>Polyunsaturated acid</strong> {{ human_attribute.polyunsaturated_acid }} </p>
<p><strong>Saturated acid</strong> {{ human_attribute.saturated_acid }} </p>
<p><strong>Monounsaturated acid</strong> {{ human_attribute.monounsaturated_acid }} </p>
<p><strong>Calcium in 100 g in mg</strong> {{ human_attribute.calcium_in_mg }} </p>
<p><strong>Phosphorus in 100 g in mg</strong> {{ human_attribute.phosphorus_in_mg }} </p>
<p><strong>Magnesium in 100 g in mg</strong> {{ human_attribute.magnesium_in_mg}} </p>
<p><strong>Potassium in 100 g in mg</strong> {{ human_attribute.potassium_in_mg }} </p>
<p><strong>Sodium in 100 g in mg</strong> {{ human_attribute.sodium_in_mg }} </p>
<p><strong>Chlorine in 100 g in mg</strong> {{ human_attribute.chlorine_in_mg }} </p>
<p><strong>Sulfur in 100 g in mg</strong> {{ human_attribute.sulfur_in_mg }} </p>
<p><strong>Iron in 100 g in mg</strong> {{ human_attribute.iron_in_mg }} </p>
<p><strong>Zinc in 100 g in mg</strong> {{ human_attribute.zinc_in_mg }} </p>
<p><strong>Iodine in 100 g in mg</strong> {{ human_attribute.iodine_in_mg }} </p>
<p><strong>Fluorine in 100 g in mg</strong> {{ human_attribute.fluorine_in_mg }} </p>
<p><strong>Thiamine vitamin B1 in 100 g in mg</strong> {{ human_attribute.thiamine_vitamin_B1_in_mg }} </p>
<p><strong>Riboflavin vitamin B2 in 100 g in mg</strong> {{ human_attribute.riboflavin_vitamin_B2_in_mg }} </p>
<p><strong>Pyridoxine vitamin B6 in 100 g in mg</strong> {{ human_attribute.pyridoxine_vitamin_B6_in_mg }} </p>
<p><strong>Pantothenic acid vitamin B3 in 100 g in mg</strong> {{ human_attribute.pantothenic_acid_vitamin_B3_in_mg }} </p>
<p><strong>Folacin acid vitamin B9 in 100 g in mcg</strong> {{ human_attribute.folacin_acid_vitamin_B9_in_mcg }} </p>
<p><strong>Cobalamin acid vitamin B12 in 100 g in mcg</strong> {{ human_attribute.cobalamin_acid_vitamin_B12_in_mcg }} </p>
<p><strong>Niacin vitamin PP in 100 g in mg</strong> {{ human_attribute.niacin_vitamin_PP_in_mg }} </p>
<p><strong>Ascorbic acid vitamin C in 100 g in mg</strong> {{ human_attribute.ascorbic_acid_vitamin_C_in_mg }} </p>
<p><strong>Retinol vitamin A in 100 g in mcg</strong> {{ human_attribute.retinol_vitamin_A_in_mcg }} </p>
<p><strong>Tocopherol vitamin E in 100 g in mg</strong> {{ human_attribute.tocopherol_vitamin_E_in_mg }} </p>
<p><strong>Cholecalciferol vitamin D in 100 g in mcg</strong> {{ human_attribute.cholecalciferol_vitamin_D_in_mcg }} </p>
<p><strong>Energy value in kcal</strong> {{ human_attribute.energy_value_in_kcal }} </p>
{% endfor %}
{% endblock %}

product_database/catalog/templates/catalog/balancednutritionformula_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Country List</h1>
{% if balancednutritionformula_list %}
<ul>
    {% for bnf in balancednutritionformula_list %}
    <li>
        <a href="{{ bnf.get_absolute_url }}">{{ bnf.country }}</a> {% if user.is_authenticated %}- <a href="{% url 'renew-bnf' bnf.id %}">Renew</a>  {% endif %}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

product_database/catalog/templates/catalog/balancednutritionformula_renew.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}
<script src="{% static 'js/jquery-1.3.2.min.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $(function() {
        $('#myForm tbody tr').formset({
            prefix: '{{ formset.prefix }}'
        });
    })
</script>

<h1>Country: {{ balanced_nutrition_formula_inst.country }}</h1>
{% for human_attribute in balanced_nutrition_formula_inst.human_attributes.all %}
<p><strong>Proteins in 100 g</strong> {{ human_attribute.proteins_in_100_g }} </p>
<p><strong>Proteins in 100 g including animals</strong> {{ human_attribute.proteins_in_100_g_including_animals }} </p>
<p><strong>Fat in 100 g</strong> {{ human_attribute.fat_in_100_g }} </p>
<p><strong>Fat in n100 g including animals</strong> {{ human_attribute.fat_in_100_g_including_animals }} </p>
<p><strong>Digestible carbohydrates in 100 g</strong> {{ human_attribute.digestible_carbohydrates_in_100_g }} </p>
<p><strong>Digestible carbohydrates in 100 g including mono and disaccharides</strong> {{ human_attribute.digestible_carbohydrates_in_100_g_incl_m_and_d }} </p>
<p><strong>Dietary fiber in 100 g</strong> {{ human_attribute.dietary_fiber_in_100_g }} </p>
<p><strong>Dietary fiber in 100 g including fiber and pectin</strong> {{ human_attribute.dietary_fiber_in_100_g_including_fiber_and_pectin }} </p>
<p><strong>Polyunsaturated acid</strong> {{ human_attribute.polyunsaturated_acid }} </p>
<p><strong>Saturated acid</strong> {{ human_attribute.saturated_acid }} </p>
<p><strong>Monounsaturated acid</strong> {{ human_attribute.monounsaturated_acid }} </p>
<p><strong>Calcium in 100 g in mg</strong> {{ human_attribute.calcium_in_100_g_in_mg }} </p>
<p><strong>Phosphorus in 100 g in mg</strong> {{ human_attribute.phosphorus_in_100_g_in_mg }} </p>
<p><strong>Magnesium in 100 g in mg</strong> {{ human_attribute.magnesium_in_100_g_in_mg}} </p>
<p><strong>Potassium in 100 g in mg</strong> {{ human_attribute.potassium_in_100_g_in_mg }} </p>
<p><strong>Sodium in 100 g in mg</strong> {{ human_attribute.sodium_in_100_g_in_mg }} </p>
<p><strong>Chlorine in 100 g in mg</strong> {{ human_attribute.chlorine_in_100_g_in_mg }} </p>
<p><strong>Sulfur in 100 g in mg</strong> {{ human_attribute.sulfur_in_100_g_in_mg }} </p>
<p><strong>Iron in 100 g in mg</strong> {{ human_attribute.iron_in_100_g_in_mg }} </p>
<p><strong>Zinc in 100 g in mg</strong> {{ human_attribute.zinc_in_100_g_in_mg }} </p>
<p><strong>Iodine in 100 g in mg</strong> {{ human_attribute.iodine_in_100_g_in_mg }} </p>
<p><strong>Fluorine in 100 g in mg</strong> {{ human_attribute.fluorine_in_100_g_in_mg }} </p>
<p><strong>Thiamine vitamin B1 in 100 g in mg</strong> {{ human_attribute.thiamine_vitamin_B1_in_100_g_in_mg }} </p>
<p><strong>Riboflavin vitamin B2 in 100 g in mg</strong> {{ human_attribute.riboflavin_vitamin_B2_in_100_g_in_mg }} </p>
<p><strong>Pyridoxine vitamin B6 in 100 g in mg</strong> {{ human_attribute.pyridoxine_vitamin_B6_in_100_g_in_mg }} </p>
<p><strong>Pantothenic acid vitamin B3 in 100 g in mg</strong> {{ human_attribute.pantothenic_acid_vitamin_B3_in_100_g_in_mg }} </p>
<p><strong>Folacin acid vitamin B9 in 100 g in mcg</strong> {{ human_attribute.folacin_acid_vitamin_B9_in_100_g_in_mcg }} </p>
<p><strong>Cobalamin acid vitamin B12 in 100 g in mcg</strong> {{ human_attribute.cobalamin_acid_vitamin_B12_in_100_g_in_mcg }} </p>
<p><strong>Niacin vitamin PP in 100 g in mg</strong> {{ human_attribute.niacin_vitamin_PP_in_100_g_in_mg }} </p>
<p><strong>Ascorbic acid vitamin C in 100 g in mg</strong> {{ human_attribute.ascorbic_acid_vitamin_C_in_100_g_in_mg }} </p>
<p><strong>Retinol vitamin A in 100 g in mcg</strong> {{ human_attribute.retinol_vitamin_A_in_100_g_in_mcg }} </p>
<p><strong>Tocopherol vitamin E in 100 g in mg</strong> {{ human_attribute.tocopherol_vitamin_E_in_100_g_in_mg }} </p>
<p><strong>Cholecalciferol vitamin D in 100 g in mcg</strong> {{ human_attribute.cholecalciferol_vitamin_D_in_100_g_in_mcg }} </p>
<p><strong>Energy value in kcal</strong> {{ human_attribute.energy_value_in_kcal }} </p>
{% endfor %}

<h1>Human attributes renew</h1>
    <form id="myForm" method="post">
        {% csrf_token %}
        <table>
            <tbody>
            {% for form in formset.forms %}
                <tr id="{{ form.prefix }}-row">
                    <td style="border-bottom: 1px solid #000000">{{ form.as_p }}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
        {{formset.management_form}}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

product_database/catalog/templates/catalog/kitchenutensil_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Add Kitchen utensil</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

product_database/catalog/templates/catalog/price_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Add Price</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

product_database/catalog/templates/catalog/users_favorite_products.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Favorite products</h1>

    {% if product_list %}
    <ul>

      {% for product in product_list %}
      <li>
        <a href="{{product.get_absolute_url}}">{{product.name}}</a>
        - <a href="{% url 'delete_product_from_favorite' product.id %}">Delete from favorite</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no favorite products.</p>
    {% endif %}
{% endblock %}